import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Web3 from 'web3';
import { useEffect, useState } from 'react';

declare let window: any;
let from: any;
let web3: any;
export default function Home() {

  const connectProvider = async() => {
    if(!window.ethereum) {
      alert('Provider is required');
      return;
  }

  await window.ethereum.request({method: 'eth_requestAccounts'});
    web3 = new Web3(window.ethereum);

    const account = await web3.eth.requestAccounts();
    from = account[0];
  }

  const submitWeb3 = (event: any) => {
    event.preventDefault();
    const { recipient, amount } = event.target;
    const to = recipient.value;

    if(Number(amount) <= 0){
      alert('Invalid amount!');
      return;
    }

    if(!web3.utils.isAddress(to)) {
      alert('Address is not valid');
      return;
    }

    web3.eth.sendTransaction({
      from: from,
      to: to,
      value: amount.value
    })
  }

  useEffect(() => {
    connectProvider();
  },[])
  

  return (
    <>
      <Head>
        <title>Web3</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
            <button onClick={connectProvider}>Connect</button>
              <br />
              <br />
            <form onSubmit={submitWeb3}>
                <label htmlFor="">Recipient</label>
                <input type="text" name='recipient' />
                <label htmlFor="">Amount</label>
                <input type="text" name='amount' />
                <button type='submit'>send</button>
            </form>
        </div>
      </main>
    </>
  )
}
